### ISSUE TITLE
Possibility of making veins non infinite

### ISSUE THREAD

**Issue by brisingraerowing** [tom5454/Create-Ore-Excavation#1]
How about an option to make veins finite, to encourage expansion to find more veins. Most other mods that have mechanics like this make veins finite by default.

**Comment by 435THz** [comment]
I honestly not only support this, but want to add a detail to it:
Adding this option as a vein property. This way it would be possible to make some veins infinite and some finite. Maybe make it have a "min" and "max" property and just roll between the two on vein gen
