### ISSUE TITLE
How should I modify the cooldown time for using the vein finder?

### ISSUE THREAD

**Issue by WhiseNT** [tom5454/Create-Ore-Excavation#101]
I have found that the cooldown of the vein finder is too long,but I don't know how to change it.Could you provide a method to adjust this through KubeJS?
![图片](https://github.com/tom5454/Create-Ore-Excavation/assets/107616400/d07a696c-20b9-41f6-b7c6-3af62889b713)

**Comment by tom5454** [comment]
There is a config option `veinFinderCd`.
