### ISSUE TITLE
computercraft compatability - suggestion

### ISSUE THREAD

**Issue by hooded-person** [tom5454/Create-Ore-Excavation#102]
It would be really cool to have computercraft compatability so you can automate the finding of veins. this could be achieved by allowing turtles to use the ore vein finder and then returning something like a list of all veins nearby and the distance or by having a block version of the ore vein finder which acts as a pheripheral form which the turtle can get the data. the data could look something like (in JSON format this is):
```
[
  {
    "type":"iron ore vein",
    "distance": 25,
    "inChunk": true,
  },{
    "type":"copper ore vein",
    "distance": 175,
  }
]
```
or returning multiple sets of data like:
in this chunk
```
{"type":"iron ore vein", "foundVein": true}
```
then for the second data
```
[
  {
    "type":"iron ore vein",
    "distance": 25,
  },{
    "type":"copper ore vein",
    "distance": 175,
  }
]
```
In my opinion the second option would be easier to work with, but the first option would provide a bit more of a challenge

**Comment by CinnamonShaey** [comment]
i see compatability has been added, can i ask how it workd? like what are the commands? how do i make program that searches for veins?

**Comment by hooded-person** [comment]
I have also requested this in #107. I will post what I have figured out so far in there later.
