### ISSUE TITLE
Can't find veins added for Mekanism and Mystical Agriculture ores

### ISSUE THREAD

**Issue by darthvader45** [tom5454/Create-Ore-Excavation#106]
I added veins for Mekanism's Osmium, Lead, Uranium, Fluorite and Tin, as well as inferium, prosperity and soulium from mystical agriculture and can't seem to find them.  I checked and double-checked my .js files and there were no errors loading them in, so I have no clue what the issue could be.  Is there something wrong with the files that doesn't register as an error?

Server scripts:
[server_scripts.zip](https://github.com/user-attachments/files/16354526/server_scripts.zip)

**Comment by tom5454** [comment]
If all three of the placement values match, the veins overlap with each other and the mod picks the highest priority one.
You can change the last number which is the random salt, it doesn't effect the rarity of the placement, just prevents overlapping the veins.

**Comment by darthvader45** [comment]
Thanks, changed all the values and ended up getting em.  Will make sure to take advantage of all the ore I can get my hands on.
