### ISSUE TITLE
computercraft documentation

### ISSUE THREAD

**Issue by hooded-person** [tom5454/Create-Ore-Excavation#107]
please add documentation explaining what the values returned by `veinfinder.search()`. i have only been able to deduce that if the second value is `True` that then the third value will be the string of which ore vein was found. i am not able to understand the number that follows or the n=
also the first boolean seems to always be true. Would it be possible to recieve some clarifacation on what these values mean precisly?

**Comment by tom5454** [comment]
It's: `local useSuccess, veinFound, veinId, veinSize = finder.search()`. veinSize 0 is inifinite.

**Comment by hooded-person** [comment]
> It's: `local useSuccess, veinFound, veinId, veinSize = finder.search()`. veinSize 0 is inifinite.

You forgot the fact that it always comes with n=length as last argument for some reason
