### ISSUE TITLE
Add support for the basic biome dictionary

### ISSUE THREAD

**Issue by CoolerGangster** [tom5454/Create-Ore-Excavation#14]
taiga
extreme_hills
jungle
mesa
plains
savanna
icy
the_end
beach
forest
ocean
desert
river
swamp
mushroom
nether

Reason being: the tags youre given by vanilla like forge:is_jungle are incomplete

**Comment by OnlyMadGab** [comment]
im struggling too much with this thing...

trying to do an addon mod for Ad Astra and didn't know why the biome wishlist isn't working at all

i tried like:
forge:is_moon
ad_astra:is_lunar_wastelands

(tried without the is_ too but didn't worked too)

i checked if the Ad Astra mod was putting the correct tag of dimension/biome and it's all correct

**Comment by Druivenpasta** [comment]
Was digging around, and I am trying to develop a modpack involving digging coal in the earlygame.
I can confirm this issue on 1.19.2.

**Comment by tom5454** [comment]
Biome Dictionary was removed from forge in favour of tags in 1.18
