### ISSUE TITLE
Issues with kubejs and fluid extracting

### ISSUE THREAD

**Issue by SkarKorlan13** [tom5454/Create-Ore-Excavation#17]
2 issues:

1. The KubeJS function event.recipes.createoreexcavation.extracting() doesn't seem to work. I copied and pasted the example code from the KubeJS section on the github and it doesn't create a recipe in the fluid extracting section in JEI. I used event.custom() and got it working so I'm guessing there's an error in the KubeJS extracting() function.

2. Even though my event.custom() function shows a fluid extracting recipe in JEI it doesn't seem to actually spawn it in world. I looked around with the Ore Vein Finder for a few minutes, didn't find it, increased the weight to 100, didn't find it, increased to 10000, and I still can't find it. I also couldn't find the built-in water vein while searching. The item drilling recipes work perfectly in every way. No issues there.

**Comment by Fail-gh** [comment]
KubeJS for 1.19.2 changed the syntax see: https://mods.latvian.dev/books/kubejs/page/migrating-to-kubejs-6
With "ServerEvents.recipes(event => {" there's no error, but still not working, so i think that is a CreateOreExcavation problem

**Comment by reimannsum** [comment]
The biome whitelist and blacklist tags need to be minecraft:is-{dimention} not forge.

**Comment by reimannsum** [comment]
@tom5454
