### ISSUE TITLE
Suggestion: Changes to alleviate quirks with current generation system

### ISSUE THREAD

**Issue by CvoidWyvern** [tom5454/Create-Ore-Excavation#21]
After going through the configs and source code of this mod, I saw that a lot of things I'd want to use this mod for aren't possible with the current system. Correct me if I'm wrong but from what I can see:

- You cannot make a vein spawn in 100% of chunks in a biome/dimension due to the generationChance config not allowing values below 1.
- Increasing the weight of a vein that only spawns in 1 biome and 1 dimension will decrease the current spawn rate of all other veins in all other biomes and dimensions, and decrease the highest possible spawn rate of those veins.
- There's no way to force a chunk to contain a vein, for the purpose of adventure maps or similar (if the above two weren't true then you could just add biomes with biometweaker and make certain veins exist in 100% of chunks in that biome)

Suggestions of changes that could allow these:
- Giving each vein a chance to spawn instead of weight and a priority, with higher priorities overriding lower priority veins.
- Giving each vein a chance to spawn instead of weight and allowing multiple veins per chunk.
- Generating a weighted list for each biome loaded instead of one for everything, allowing generationChance to be set to zero and overridden for each. Could instead just make one of those lists when there's something that would modify that list and just default to the original otherwise. This may allow the best backwards compatibility of all of these since in existing worlds each weighted list would be the same as the old one.
- #12, with biome being a possible recipe modifier, and allowing generationChance to be set to zero.

**Comment by tom5454** [comment]
Added a `/coe setvein` command in the latest release.
I will rewrite the ore vein generation system for the next minecraft version (1.20), it will make the veins and extracting recipes separate.
