### ISSUE TITLE
Incompatible with Block Swap

### ISSUE THREAD

**Issue by An-thracene** [tom5454/Create-Ore-Excavation#27]
https://www.curseforge.com/minecraft/mc-mods/block-swap-fabric
Version: 1.19.2-Fabric-0.14.19
Mods:
Block+Swap-fabric-1.19-2.0.0.0
create-fabric-0.5.0.i-991+1.19.2
createoreexcavation-fabric-1.19-1.1.1
fabric-api-0.76.0+1.19.2

**Comment by tom5454** [comment]
What is the incompatibility? Is it crashing?
Please post your minecraft log

**Comment by An-thracene** [comment]
It crashed and here are the log and the crash report
[latest.log](https://github.com/tom5454/Create-Ore-Excavation/files/11239086/latest.log)
[crash-2023-04-15_18.12.31-client.txt](https://github.com/tom5454/Create-Ore-Excavation/files/11239087/crash-2023-04-15_18.12.31-client.txt)
