### ISSUE TITLE
Mod Load Error

### ISSUE THREAD

**Issue by ZEROX7** [tom5454/Create-Ore-Excavation#3]
so your mod wont load on newest Flywheel version:
![image](https://user-images.githubusercontent.com/12628051/184707080-b7342bc4-263f-48b7-9cd4-2c3f6448c87a.png)

**Comment by Delfite** [comment]
This seems to be a common problem with a lot of Create addons and it's getting pretty damn annoying

**Comment by 435THz** [comment]
Listen guys
If create literally just updated, it only makes sense that the addons might need to be updated as well, and that takes time as well. It's not a hard concept to grasp, you know?

**Comment by Delfite** [comment]
> Listen guys If create literally just updated, it only makes sense that the addons might need to be updated as well, and that takes time as well. It's not a hard concept to grasp, you know?

You sound upset over what is no longer an issue.
