### ISSUE TITLE
is_nether tag broken

### ISSUE THREAD

**Issue by TheSpartan696** [tom5454/Create-Ore-Excavation#30]
Was making a KubeJs script, everything was working properly until i was trying to import ancient debris into the list. All of immersive engineering was working but for some reason the Nether tag is broken. Any fix? I noticed that is_end tag was working perfectly fine so idk whats going on.
![image](https://user-images.githubusercontent.com/127004713/235337020-07b6a095-ade6-42c8-9513-e53243f1cfb2.png)

**Comment by tom5454** [comment]
You have to use `minecraft:is_nether`, forge doesn't have that tag only `is_overworld` and `is_end`.
