### ISSUE TITLE
Create update [v0.5.1a] (for 1.18.2) broke the mod

### ISSUE THREAD

**Issue by Fridelit** [tom5454/Create-Ore-Excavation#32]
Latest Create update [v0.5.1a] (for 1.18.2) broke this mod. 1 error during loading

Create Ore Excavation (createoreexcavation) has failed to load correctly
java.lang.NoClassDefFoundError: com/simibubi/create/foundation/block/BlockStressValues$IStressValueProvider

**Comment by tom5454** [comment]
Fixed in the latest update
