### ISSUE TITLE
Datapack Compatibility?

### ISSUE THREAD

**Issue by dragonshardz** [tom5454/Create-Ore-Excavation#38]
I am trying to add ore veins using Minecraft's built-in datapack functions, and the mod doesn't seem to recognize them even if they're in the right directory implied by the structure of the mod's data.

Does this mod support adding ore veins with datapacks, or only via KubeJS?

**Comment by dragonshardz** [comment]
Here you go!

[drilling.zip](https://github.com/tom5454/Create-Ore-Excavation/files/11853158/drilling.zip)

The files are loose in a global pack loader's resource folder; the full path they're located at is `C:\Games\Minecraft\instances\Transylgoonia 2.0 Test\.minecraft\global_packs\required_data\progress_recipes\data\progress_recipes\recipes\drilling`

**Comment by tom5454** [comment]
The name field in the json is a text component, so you have to write `"name": "{\"text\":\"Lapis Lazuli\"}",`

**Comment by dragonshardz** [comment]
That doesn't seem to work. The veins still do not show up.
