### ISSUE TITLE
[1.20.1] Datapack does not work

### ISSUE THREAD

**Issue by lays24mc** [tom5454/Create-Ore-Excavation#46]
I have made my own datapack. Rather said I try it. As an example I would like to include the Prosperity Shard from Mystical Agriculture. Unfortunately, the game does not take this. Neither in JEI it is displayed nor can I find it with " coe locate". Am I doing something wrong, or is this not working the way I think it should? Datapacks are still quite new to me :D

Here my zip :)

[createoreexcavation.zip](https://github.com/tom5454/Create-Ore-Excavation/files/12172557/createoreexcavation.zip)

**Comment by tom5454** [comment]
Your datapack folders are not correct, it must be `data/<your pack name>/recipes/drilling/...`

**Comment by lays24mc** [comment]
Thanks for the hint. I had somehow totally overlooked, although I had checked it several times xD
