### ISSUE TITLE
Ore excavation

### ISSUE THREAD

**Issue by SaulGoodman694** [tom5454/Create-Ore-Excavation#47]
Would I require it to be in the chunk or for it to be traces as currently even If I replaced everything but the specificed ore such as coal and then I put the drill on it, It says No vein to excavate, How do I fix this

**Comment by Bitgedon** [comment]
What? 

This isn't a help center, can you describe the issue better?

**Comment by tom5454** [comment]
If you changed the vein recipes, it used to show the `found traces...` but the ore vein isn't there anymore.
Update to the latest version.
