### ISSUE TITLE
please Help KubeJS

### ISSUE THREAD

**Issue by WAP2080560553** [tom5454/Create-Ore-Excavation#51]
I would like to know how do I add to the drilling to excavate amethyst shard infinitely using kubejs?
I did it like this, is it correct?
```
ServerEvents.recipes(event => {
	//Drilling recipes (Items)
	//Spawning weight the bigger the number the higher chance to spawn.
	//See server config for empty chunk weight.
	//Arguments: output item(s), ore vein name in Text Component, spawning weight, extraction time in ticks at 32 RPM.
    event.recipes.createoreexcavation.drilling('minecraft:amethyst_shard', '{"text": "amethyst shard"}', 40, 100).alwaysInfinite().id("amethyst_shard");
});
```
Tell me if it's correct
I want him to mine amethyst shards in the The Twilight Forest dimensionand other minerals.(At present, I am just trying to add recipes and research whether to specify dimension mining, because I am not very good at KubeJS).
I try to add the recipe but the vein recipe can't be loaded.(Pressing U on the drill has no recipes. Sorry, English is not my mother tongue. Hope the author can write a downloadable JSON example for reference, because it is prompted in Visual Studio Code: Expected a JSON object, array or literal) . KubeJS version: 6.1, game version 1.19.2

**Comment by tom5454** [comment]
It's not a `.json` file it's a `.js` file.
You can only filter for biomes and not dimensions.
Here is a liveroot drilling recipe as a template:
```
event.recipes.createoreexcavation.drilling('twilightforest:liveroot', '{"text": "Liveroot"}', 10, 100)
.veinSize(3, 8.5)
.biomeWhitelist('twilightforest:in_twilight_forest')
.id("liveroot");
```

**Comment by WAP2080560553** [comment]
Thank you for your answers to the questions and support for the magic reform, maybe my reply is a bit late, thank you very much.
