### ISSUE TITLE
How to understand .placement argument?

### ISSUE THREAD

**Issue by MisterZam** [tom5454/Create-Ore-Excavation#56]
In the .placement argument, there is spacing, separation, and salt. What do these mean? Also si there going to be a way to have multiple ores in a chunk or di i need to do a randomized Item.of? Thank you in advance

**Comment by tom5454** [comment]
It works like the vanilla random structure placement
https://minecraft.wiki/w/Custom_structure#JSON_format
You can only have one vein but multiple recipes for one vein (different drills, different drilling fluid, or multiple items with random chances).
