### ISSUE TITLE
Ore finder does not work in 1.20.1

### ISSUE THREAD

**Issue by WinryGames** [tom5454/Create-Ore-Excavation#57]
![image](https://github.com/tom5454/Create-Ore-Excavation/assets/148687953/72c8d44b-349f-4b6f-ab9f-19f392dac554)

When using the ore vein finder, it comes up with the chunk coords but does not say what vein it has found or where it has found it.

**Comment by tom5454** [comment]
Please post your minecraft log

**Comment by tom5454** [comment]
Most likely a hammerlib incompatibility like #61, fixed in the latest version
