### ISSUE TITLE
Require veins to be naturally generated for drilling

### ISSUE THREAD

**Issue by genesy** [tom5454/Create-Ore-Excavation#6]
Currently can be abused by silktouching ores and drilling these with my tests

**Comment by tom5454** [comment]
The ore veins generate inside the chunk data, you cannot move them in-game, they are not in the world. You may have the wrong mod.

**Comment by genesy** [comment]
i mean within the chunk if i silk touch an ore and place them somewhere else, they're still drillable...

**Comment by tom5454** [comment]
You don't need ore blocks to drill, you can place the drill anywhere in the chunk and it will extract resources, and you can place multiple drills in one chunk (for now). You can extract with hundreds of drills if you can supply the stress units required.

**Comment by genesy** [comment]
oh lol didn't even realize. are there plans to make it so that it needs blocks or is it just chunk based ?
