### ISSUE TITLE
Having a freedom to add own drills?

### ISSUE THREAD

**Issue by MisterZam** [tom5454/Create-Ore-Excavation#60]
I know there is a way using kubejs is just that a lot of people including me dont know yet.  Would it be possible to have a kubejs easy compat for adding drills? Thank youu

**Comment by tom5454** [comment]
You have to add the item to the `#createoreexcavation:drills` tag, either with KubeJS or with a datapack.
And place a texture for the 3D drill model into a resourcepack under: `assets/<item mod id>/textures/entity/drill/<item name>.png`.
[Here is the default texture](https://github.com/tom5454/Create-Ore-Excavation/blob/main/Forge/src/platform-shared/resources/assets/createoreexcavation/textures/entity/drill/drill.png)
