### ISSUE TITLE
excavator crashes game

### ISSUE THREAD

**Issue by Tsumiki129** [tom5454/Create-Ore-Excavation#61]
hi im helping testing a mod pack for minecolonies dimensional adventure and are testing for a new update but have found that the excavator is crashing the game for ticking block entity on another note with this we also cant get the vain miner to work and tell us what's in the chunk but the main isue right now is it is crashing are game. 

Minecraft 1.2.0 forge version 47.2.1

here is the crash log not to sure if this has worked for the link 

[crash-2023-10-31_17.37.02-server.txt](https://github.com/tom5454/Create-Ore-Excavation/files/13230031/crash-2023-10-31_17.37.02-server.txt)

**Comment by tom5454** [comment]
One of your mods is crashing in a mixin `net.minecraft.world.item.crafting.RecipeManager.handler$zba000$replaceRecipeId`.
Add the `-Dmixin.debug.verbose=true` jvm argument then send me the log when it crashes.

**Comment by Tsumiki129** [comment]
sorry for the long wait i have now tested with the augment on gone onto a single player super flat creative world and placed the mining drill and game crashed  here is the log for it

[crash-2023-10-31_17.37.02-server.txt](https://github.com/tom5454/Create-Ore-Excavation/files/13242779/crash-2023-10-31_17.37.02-server.txt)

**Comment by tom5454** [comment]
That's the same crash report. Please send me the minecraft log from your logs folder called `latest` or `latest.log`.

**Comment by Tsumiki129** [comment]
my bad sorry kind of new to all this bit here is the latest log

[latest.log](https://github.com/tom5454/Create-Ore-Excavation/files/13260363/latest.log)

**Comment by Tsumiki129** [comment]
i have a bit of ann update so it looks like what you said with another mod posibly causing it since we have another bug with stacks from a difrent mod i have been going through the pack serching for it and have found hammerlib is braking your excavator mod with the crash and vainfinder not working
