### ISSUE TITLE
[Fabric 1.20.1] Unable to find modded biomes with a biomewhitelist in KubeJS

### ISSUE THREAD

**Issue by DCobley** [tom5454/Create-Ore-Excavation#62]
Ive been unable to find modded biomes with a biomewhitelist in KubeJS, I believe im doing it correctly but havent had much success with it. Ive been attempting specifically to get a Terralith biome (Yellowstone). 

If I simply use minecraft:in_overworld I am able to get all those modded biomes, just not individually.

`event.recipes.createoreexcavation.vein('{"text": "Calcite"}', 'minecraft:calcite').placement(128, 64, 5552352).veinSize(3, 8.5).biomeWhitelist('terralith:yellowstone').id("kubejs:calcite_vein")`

![image](https://github.com/tom5454/Create-Ore-Excavation/assets/9076948/d6e65527-c9fd-4e61-b2fe-ec14f9ee6244)

**Comment by tom5454** [comment]
Create a custom biome tag with a single biome and use that in the recipe.
```js
ServerEvents.tags('worldgen/biome_source', event => {
	event.add('kubejs:yellowstone', 'terralith:yellowstone')
})
```

```js
event.recipes.createoreexcavation.vein('{"text": "Calcite"}', 'minecraft:calcite').placement(128, 64, 5552352).veinSize(3, 8.5).biomeWhitelist('kubejs:yellowstone').id("kubejs:calcite_vein")
```

**Comment by DCobley** [comment]
Thank you, I suppose I shouldve looked more deeply into the kubejs documentation first. Sorry to bother!
