### ISSUE TITLE
[Question] Creating Ore Veins in already generated Chunks

### ISSUE THREAD

**Issue by Semorphim** [tom5454/Create-Ore-Excavation#63]
Hi,

we decided to add this Mod to our existing Fabric 1.20.1 Server. It is working as intended but the first Veins are generated about 2k Blocks from Spawn.

Because we already explored quite a bit I dont want to remove old chunks to force a new gen.

Is there a way to regen the Ore Veins for this mod via command or removing a specific .dat?

**Comment by tom5454** [comment]
The veins only generate when you check it with the vein finder or place a drilling machine, so it should work in already generated chunks.
It is normal to find veins in a few-k blocks away, in most cases.
You can set specific veins using the /coe setvein command.
