### ISSUE TITLE
Can't seem to find added vein

### ISSUE THREAD

**Issue by Alexstool** [tom5454/Create-Ore-Excavation#67]
So i just coded a new vein in kubejs for ancient debris, which should spawn in the nether. It appears in game as one of the veins the machine can drill, but I feel like I've just spent an hour exploring thousands of chunks and didn't find it. Is it normal for it to be rare ? Did I forget smth ? How can I (if possible) find a vein faster ?

**Comment by tom5454** [comment]
If you are on 1.20 you can use `/coe locate <id>` command. You have to adjust the spawning properties to change it's rarity (increasing the spawning weight value on 1.19 or older, or tweaking the `.placement(<spacing>, <separation>, <seed>)` values on 1.20)

**Comment by Alexstool** [comment]
thank you ! I changed the separation and placement value and they seemed to appear much more often
