### ISSUE TITLE
Ore veins from other mods?

### ISSUE THREAD

**Issue by Casmin7** [tom5454/Create-Ore-Excavation#71]
I am using [this](https://modrinth.com/mod/geocluster) mod for ore gen and was wondering if it would be possible somehow to make the drills work only on nods from this mod and output the right ore/ores depending on the chunk. Thank you for your help and sorry for issue spam, I couldn't find a discord server and that's probably intentional

**Comment by tom5454** [comment]
The mod uses it's own chunk based ore vein system. If the Geocluster veins have their own biome then you can create a vein that only spawns in that biome.
