### ISSUE TITLE
JEI incorrectly shows raw redstone ore as millable

### ISSUE THREAD

**Issue by ST-DDT** [tom5454/Create-Ore-Excavation#74]
JEI shows the raw redstone ore as millable by the small millstone, but it isn't.

![grafik](https://github.com/tom5454/Create-Ore-Excavation/assets/1579362/4fb6b91c-5188-441d-b96b-935aa183ab6e)
![grafik](https://github.com/tom5454/Create-Ore-Excavation/assets/1579362/c2431605-c77b-4043-b496-bd5dc20b9273)

### Reproduction Steps

- Place a small millstone and power it
- Throw a raw redstone ore in it
- Wait a minute
- Right click the millstone and you get the raw redstone ore back

### Expected behaviour

- Either get redstone dust
- Or not having the JEI recipe show up

### Versions

- createoreexcavation-fabric-1.20-1.4.3 (also reproducible on 1.4.0, didn't test older versions)

**Comment by tom5454** [comment]
Create fabric bug.
Please report it to create-fabric.
Milling recipes break if an item can be processed in a millstone and crushing wheel. (The built in wool to string recipe is also broken).

**Comment by ST-DDT** [comment]
Done:

- https://github.com/Fabricators-of-Create/Create/issues/1398

**Comment by tom5454** [comment]
The redstone milling recipe is missing it's duration so it doesn't work, but can be inserted into the millstone.
On Create Fabric this locks up the millstone after removing the item and it won't accept any items until break and replace (works correctly on Forge).
I'm releasing a patch to fix the missing duration.

**Comment by TropheusJ** [comment]
so this isn't a Create issue?
