### ISSUE TITLE
request for additional information for data pack

### ISSUE THREAD

**Issue by sirR0bson** [tom5454/Create-Ore-Excavation#76]
Hello, I have created a data pack for my own modpack from TFC.
I would like to ask for information about what values can be used in the section - placement
specifically salt, separation, spacing, prioryty.
I would be grateful if you could indicate the ranges or specific values that can be used.

`
{
  "type": "createoreexcavation:vein",
  "amountMax": 25.0,
  "amountMin": 8.0,
  "biomeWhitelist": "tfc:is_vein",
  "icon": {
    "item": "tfc:ore/small_native_copper"
  },
  "name": "{\"translate\":\"Stannite vein\"}",
  "placement": {
    "salt": 2078084124,
    "separation": 8,
    "spacing": 128
  },
  "priority": 0
}

`

**Comment by tom5454** [comment]
It works like the vanilla structure placement with a `random_spread` type. See the [Minecraft Wiki](https://minecraft.wiki/w/Structure_set#JSON_format)
