### ISSUE TITLE
After adding the packet /coe locate Invalid

### ISSUE THREAD

**Issue by meishiffx** [tom5454/Create-Ore-Excavation#77]
Version:
[fabric-1.20.1-1.4.3](https://www.curseforge.com/minecraft/mc-mods/create-ore-excavation/files/5007613)

Related modules：
[Powah-5.0.4.jar](https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected/files/4854155)       
[createaddition-fabric+1.20.1-0.9.0.jar](https://www.curseforge.com/minecraft/mc-mods/createaddition/files/4733849)

I try to add related recipe.But after adjusting once, locate can no longer be used.I guess this is not normal.Maybe it has something to do with the seed I used?

Seed：
9117625553825665749

Datapack:
[uraninite&bioethanol.zip](https://github.com/tom5454/Create-Ore-Excavation/files/14077447/uraninite.bioethanol.zip)

**Comment by tom5454** [comment]
I can't reproduce the issue with the latest version.
