### ISSUE TITLE
Command to locate ore veins?

### ISSUE THREAD

**Issue by 2-bithacker** [tom5454/Create-Ore-Excavation#78]
Is there a command to locate ore veins? Is ore vein placement determined by the world seed, or is it random? I have not been able to find a biome that has to do with ore excavation in the list. Am i doing something wrong?

**Comment by wolfieboy09** [comment]
![image](https://github.com/tom5454/Create-Ore-Excavation/assets/105564186/6190f76b-f4f8-440d-97a7-b49c5cf6cdbe)
do that

**Comment by 2-bithacker** [comment]
thx

**Comment by THEKINGSKULL01** [comment]
I'm having a issue using this command in 1.20.1
