### ISSUE TITLE
How to get REDSTONE DUST

### ISSUE THREAD

**Issue by wolfieboy09** [tom5454/Create-Ore-Excavation#81]
So once I obtain `Raw Redstone`, how do I cook it

**Comment by tehmilcho** [comment]
Regarding to recipets it should be work by milling 

![image](https://github.com/tom5454/Create-Ore-Excavation/assets/22918349/14296daa-1adf-499d-87ff-1394223bdd01)

But its not working by for me .. the Mill will accept the Item but will not something with it.

**Comment by tehmilcho** [comment]
It seems to work fine with Crushing Wheels .. there no recipets shown for .. but i tested it and its working for me

**Comment by tom5454** [comment]
Duplicate of #74
