### ISSUE TITLE
Compatibility With Journeymap

### ISSUE THREAD

**Issue by Cyranos** [tom5454/Create-Ore-Excavation#82]
Per the title I was thinking it would be really nice to add a feature for when you scan with the ore scanner it would also add an image of the ore / fluid on Journeymap if it is installed with an ability to mark it as depleted if the mod is configured to not have infinite ore, similar to how Greg Tech New Horizons Prospector Scanner works I've provided a video that shows how it works in GTNH [here](https://youtu.be/4cwqXEJkHTc) in a unlisted Youtube video.

**Comment by tom5454** [comment]
The 1.20.1 version has JourneyMap overlays.

**Comment by Cyranos** [comment]
Odd I just tested it and sure enough, apologies! I never noticed it before, which is odd, though I was curious if it would be possible to only have one circle for when your searching active at a time? Or maybe a config value for how many there are & possibly how long they stick around?

**Comment by MisterZam** [comment]
Speaking of journey map, is there a way to remove the vein mark of a chunk in the map? I have depleted this one specific chunk and i want it to stop showing in the map to not confuse my self with other chunks that are not empty. Thank you in advance
