### ISSUE TITLE
Entering server error on first time, work fine on second

### ISSUE THREAD

**Issue by LittleLigr** [tom5454/Create-Ore-Excavation#89]
Hello! I (and my friends) catching strange error when we trying to connect to server. This problem occur only on first enter, after client crash and re enter everything works fine.

Minecraft 1.20.1 Fabric

https://gist.github.com/LittleLigr/c230e806e42b6551a6a31d90721598dd

**Comment by tom5454** [comment]
It's `Dynamic Surroundings` throwing an error.
