### ISSUE TITLE
Higher grade drills mine faster?

### ISSUE THREAD

**Issue by wrincewind** [tom5454/Create-Ore-Excavation#91]
Right now, drill tiers exist only to gate resource mining - if you're mining up something that requires an iron drill, there's no reason to use a diamond or netherite one. 

What do you think about giving higher tier drills a speed bonus for mining? Mining with a diamond drill is 1.5x faster than an iron drill, and a netherite drill could be 2x faster than an iron one, for example. It'd give a reason to use more powerful drillbits.

**Comment by KaapaTeelb** [comment]
I thought that's the reason to upgrade stuff, made iron drill, then diamond, didn't notice time difference, made netherite, compared, there was no difference in speed they all are exactly 7.15 sec to mine at max speed each

**Comment by tom5454** [comment]
You can create recipes with faster mining speed, or additional items with a datapack or KubeJS. Use the `priority` setting to set which recipe should be picked.
