### ISSUE TITLE
Fabric ore vein finder does not show all veins

### ISSUE THREAD

**Issue by EricssonXD** [tom5454/Create-Ore-Excavation#92]
As said in the title, unlike the forge version, the ore vein finder in fabric does not show all veins that it manages to locate, but only the closet vein, this makes it very hard to find specific veins. I think it should be same as the forge version and show all veins rather than only the closet one

**Comment by tom5454** [comment]
The ore vein finder only shows the nearest veins in a 3x3 radius and the closest vein with the found traces... text.
