### ISSUE TITLE
Several Classes missing in Repository

### ISSUE THREAD

**Issue by abidbmt** [tom5454/Create-Ore-Excavation#93]
Im trying to modify your mod for personal use but came to the realisation that there is several classes missing in the Repository making it impossible to build the Mod

**Comment by tom5454** [comment]
If you are building Fabric you have to exit the build.gradle, change: 
https://github.com/tom5454/Create-Ore-Excavation/blob/main/Fabric/build.gradle#L187C1-L196C2
to
```gradle
sourceSets {
	main {
		java {
			srcDir "../Forge/src/platform-shared/java"
		}
		resources {
			srcDir "../Forge/src/platform-shared/resources"
		}
	}
}
```
