### ISSUE TITLE
Other ores

### ISSUE THREAD

**Issue by RA666E** [tom5454/Create-Ore-Excavation#95]
Is it possible to somehow add veins with other ores from modifications?

**Comment by tom5454** [comment]
You can create a data pack or use KubeJS.
https://github.com/tom5454/Create-Ore-Excavation/blob/main/README.md#kubejs

**Comment by RA666E** [comment]
I'm completely new to this, maybe there is some kind of guide or something?

**Comment by tom5454** [comment]
Here is the KubeJS wiki: https://kubejs.com/wiki/tutorials/recipes
And here is the example code on how to add custom veins: https://github.com/tom5454/Create-Ore-Excavation/blob/main/README.md#kubejs

**Comment by RA666E** [comment]
I managed to add ore, but I can’t find it with the detector, with the jei mod I can see in which battles the ore appears, but mine doesn’t have this list, maybe because of this? And how to increase the chance of all veins appearing?

**Comment by KEJWII** [comment]
(if it helps) Here is the code that I managed to do

**ServerEvents.recipes(event => {
	
	//Adding veins
	//.placement(spacing, separation, salt)
	//If all three values match the veins overwrite each other
	//Use .priority(<value>) to set the vein generation priority
	event.recipes.createoreexcavation.vein('{"text": "My lead vein"}', 'modern_industrialization:lead_ore')
		.placement(1024, 128, 64825185)
		.id("kubejs:my_lead_vein")
	
	//Drilling recipes (Items)
	//Arguments: output item(s), ore vein id, extraction time in ticks at 32 RPM.
	event.recipes.createoreexcavation.drilling('modern_industrialization:lead_ore', 'kubejs:my_lead_vein', 1000)
		.id("kubejs:my_vein1");

});

//Add any new drill items to #createoreexcavation:drills item tag
//Place a drill texture under assets/<item mod id>/textures/entity/drill/<item name>.png
//See assets/createoreexcavation/textures/entity/drill/drill.png**


If there are people here who also have problems with configuration and they are here for the first time CALM (I just learned a bit heh)

I put Createoreexcavationores.js file in
**.minecraft\kubejs\server_scripts**

I admit that I learned to do it very quickly with Kubejs immediately with Create Ore Excavation Mod

And it will also be useful:
https://github.com/tom5454/create-ore-excavation/blob/main/readme.md#kubies

tom5454 **VERY thank you** for this mod/addon with kubejs compatibility

**Comment by RA666E** [comment]
Is it possible to somehow increase the chance of generating a vein, for example, so that almost every chunk has one, because I flew a lot of blocks to find it, in survival it is almost useless to do this?

**Comment by KEJWII** [comment]
I do not know that yet
I would like Ore Vein Finder to work in such a way that he would look for Ores you have in your inventory (or gui in which you place the ore or allow the Toggle option so you can switch the search for ore)
