### ISSUE TITLE
Fatal (very weird) error kubejs

### ISSUE THREAD

**Issue by KEJWII** [tom5454/Create-Ore-Excavation#97]
During my coding I started to finish
I checked with every progress if everything works

And at the end when I thought it was all
Suddenly such a mistake appeared
![Base Profile Screenshot 2024 05 28 - 23 35 00 37](https://github.com/tom5454/Create-Ore-Excavation/assets/106697974/ea449f7b-5a7e-403f-9dcd-b5b2da0f5208)
![Base Profile Screenshot 2024 05 28 - 23 35 26 28](https://github.com/tom5454/Create-Ore-Excavation/assets/106697974/eeba2e46-4554-44da-82a3-9ce51ed04241)
![Desktop Screenshot 2024 05 28 - 23 38 04 85](https://github.com/tom5454/Create-Ore-Excavation/assets/106697974/7d93cf32-84f2-40e9-a459-8feb2fe3cc59)

I also feel that it may be related to Morejs which I installed after that
I removed it and the problem still occurs
I changed to the previous version of Kubejs and it doesn't work either

**Comment by tom5454** [comment]
Check line 156 in your js file. You may have removed a mod, or using an invalid item id.

**Comment by KEJWII** [comment]
You're right
today (when I write) I checked in turn
And it turned out that instead
"Modern_industrialization: monazite_ore"
I wrote
"Techreborn: monazite_ore"

In any case, I have already solved the problem and everything is already working

But I don't think I understood this displayed error because something about serverevents.recipes wrote (event => {
or
Createoreexcavation.vein

and I didn't understand what's going on
